# -*- coding: utf-8 -*-
# Numpy module
import numpy as np
# for command-line arguments
import sys
# Qt4 bindings for core Qt functionalities (non-GUI)
from PyQt5 import QtCore
# Python Qt4 bindings for GUI objects
from PyQt5 import QtGui, QtWidgets
# import the MainWindow widget from the converted .ui files
from convertisseur_gui import Ui_Convertisseur_dB

# definition des constantes
pref = 2e-5

class DesignerMainWindow(QtWidgets.QMainWindow, Ui_Convertisseur_dB):
    """Customization for Qt Designer created window"""
    def __init__(self, parent = None):
        # initialization of the superclass
        super(DesignerMainWindow, self).__init__(parent)
        # setup the GUI --> function generated by pyuic4
        self.setupUi(self)
         # connect the signals with the slots
        self.pushButton_pascal.clicked.connect(self.pascal2dB)
        self.pushButton_dB.clicked.connect(self.dB2pascal)

    def pascal2dB(self):
        print (self.pushButton_pascal.text())
        pa = float(self.lineEdit_pascal.text())
        db = 20 * np.log10(pa/pref)
        self.lineEdit_dB.setText(str(int(db)))

    def dB2pascal(self):
        self.lineEdit_pascal.setText('hello')

# create the GUI application
app = QtWidgets.QApplication(sys.argv)
# instantiate the main window
dmw = DesignerMainWindow()
# show it
dmw.show()
# start the Qt main loop execution, exiting from this script
# with the same return code of Qt application
sys.exit(app.exec_())